version: '3.8'
services:
  ladys-npm-base:
    container_name: ladys-npm-base
    tty: true
    user: root
    build:
      context: .
      dockerfile: docker/setup/webpack/Dockerfile
    volumes:
      - .:/app
