const SWEET_ALERT_SHOW = 'SWEET_ALERT_SHOW';
const SWEET_ALERT_UPDATE = 'SWEET_ALERT_UPDATE';
const SWEET_ALERT_HIDE = 'SWEET_ALERT_HIDE';
const SWEET_ALERT_HIDE_COMPLETE = 'SWEET_ALERT_HIDE_COMPLETE';

const REDUCER_SWEET_ALERT_NAME = 'sweetAlert';

export {
  SWEET_ALERT_SHOW,
  SWEET_ALERT_UPDATE,
  SWEET_ALERT_HIDE,
  SWEET_ALERT_HIDE_COMPLETE,

  REDUCER_SWEET_ALERT_NAME,
};
